
online: false

server.port: 8080

spring:
  application.name: table-column-example
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/table-column?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 2
      dataSourceProperties:
        prepStmtCacheSize: 50
        prepStmtCacheSqlLimit: 128
        cachePrepStmts: true
        useServerPrepStmts: false

query:
  table-prefix: t_
  alias-generate-rule: 10
  logic-delete-column: deleted
  logic-value: 0
  logic-delete-boolean-value: 1
  logic-delete-int-value: UNIX_TIMESTAMP()
  logic-delete-long-value: id
