
online: false

server.port: 8080

logging.config: classpath:log-dev.xml


spring:
  application.name: table-column-example
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useAffectedRows=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&queryInterceptors=com.github.liuanxin.config.ShowSqlInterceptor
    username: root
    password: root
    hikari:
      minimumIdle: 2
      maximumPoolSize: 2
      dataSourceProperties:
        prepStmtCacheSize: 50
        prepStmtCacheSqlLimit: 128
        cachePrepStmts: true
        useServerPrepStmts: false
